### ISSUE TITLE
Add GitHub actions CI workflow

### ISSUE THREAD

**Issue by otavio** [OSSystems/easysplash#1]
We can rely on GitHub actions to test the source for build and ensure every pull request does not break the builds.

**Comment by otavio** [comment]
Would you be open to extending the workflow to enable more flavors?

We could build in a matrix for some of the backends and ensure it keeps building.

**Comment by texierp** [comment]
> Would you be open to extending the workflow to enable more flavors?
> 
> We could build in a matrix for some of the backends and ensure it keeps building.

Sure, no problem, I will check that ;)
